x-service-provisioning-base: &provisioning-base
  build:
    args:
      GID: ${GID:-0}
      UID: ${UID:-0}
    context: Dockerfile.d/provisioning
  command:
    - zsh
    - -ic
    - |
      /project/scripts/provisioning.init-with-google.sh
  environment:
    - CLOUDSDK_CORE_PROJECT
    - CURRENT_ENV_NAME
    - GOOGLE_APPLICATION_CREDENTIALS=/project/config/${CURRENT_ENV_NAME}/credentials/google-cloud-keyfile.json
    - PROJECT_UNIQUE_ID
    - TF_DATA_DIR=/tmp/provisioning/.terraform.d/
    - TF_VAR_gcp_project_id=${CLOUDSDK_CORE_PROJECT}
    - TF_VAR_project_unique_id=${PROJECT_UNIQUE_ID}
  user: "${UID:-0}:${GID:-0}"
  volumes:
    - provisioning-home-developer:/home/developer
    - provisioning-home-root:/root # for macOS
    - /var/run/docker.sock:/var/run/docker.sock
    - ./Dockerfile.d:/project/Dockerfile.d
    - ./config:/project/config
    - ./provisioning:/project/workspace
    - ./scripts:/project/scripts
    - ./tmp/provisioning:/tmp/provisioning
  working_dir: /project/workspace

services:
  provisioning:
    <<: *provisioning-base
  website:
    build:
      context: Dockerfile.d/website.development
      args:
        UID: ${UID:-0}
        GID: ${GID:-0}
    command: >
      hugo server
      --baseURL http://$BIND_IP_ADDR:1313
      --bind 0.0.0.0
      --buildDrafts
    environment:
      BIND_IP_ADDR: ${BIND_IP_ADDR:-127.0.0.1}
    ports:
      - "${BIND_IP_ADDR:-127.0.0.1}:1313:1313"
    user: "${UID:-0}:${GID:-0}"
    volumes:
      - ./website:/project/website
    working_dir: /project/website
  vscode: # for prettier
    build:
      args:
        GID: ${GID:-0}
        UID: ${UID:-0}
      context: Dockerfile.d/vscode
    command:
      - bash
      - -c
      - |
        npm-check-updates --upgrade
        npm install
        npm audit fix
        sort-package-json
    user: ${UID:-0}:${GID:-0}
    volumes:
      - .:/workspace
    working_dir: /workspace
version: "3.8"
volumes:
  provisioning-home-developer:
    driver: local
  provisioning-home-root:
    driver: local
